# Generated by Django 5.2.2 on 2025-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
